# Generated by Django 5.0.2 on 2024-02-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender_name', models.CharField(max_length=50)),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=50)),
                ('shop_licence', models.ImageField(blank=True, upload_to='licence')),
                ('email', models.EmailField(max_length=254)),
                ('vender_phno', models.IntegerField()),
                ('pawd1', models.CharField(max_length=50)),
                ('pswd2', models.CharField(max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
